environment:
    name: "Acrobot-v1" # "MountainCar-v0" #"CartPole-v1"
    seeds: [1,2,3]
    population_size: 50
    target_fitness: 500.0
    random_seed: 10

training:
    number_of_generations: 200
    crossover_probability: 0.95
    add_node_probability: 0.3
    add_connection_probability: 0.3
    weight_mutation_probability: 0.9
    weight_mutation_strength: 0.35

    loss_weight_excess: 1.0
    loss_weight_disjoint: 1.0
    loss_weight_difference: 0.4